# Generated by Django 3.1.1 on 2020-10-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20201007_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='https://placekitten.com/200/300', upload_to='images/'),
        ),
    ]
