# Generated by Django 3.1.1 on 2020-10-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20201008_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='uploaded_files/images/kitten150x100.jpg', upload_to='images/'),
        ),
    ]
