# Generated by Django 3.1.1 on 2020-10-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20200930_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemons_many', to='pokedex.PokemonType'),
        ),
    ]
